[package]
name = "vartable"
version = "0.1.0"
entrypoint = "tabvar.typ"
authors = ["Le_Foucheur"]
license = "MIT"
description = "A simple package to make variation table"
repository = "https://github.com/Le-foucheur/Typst-VarTable"
categories = "visualization"
keywords = []
exclude = ["./exemples", "documentation.pdf"]